SRC_URI_append_mcm-imx8m-nano = " \
	file://0000-can-mcp25xxfd-Microchip-MCP25xxFD-Family-CAN-control.patch \
	file://0001-panel-Add-the-panel-startek-ili9881c-driver.patch \
	file://0002-Add-w25q16-support.patch \
	file://0003-rtc-abx80x-Enable-SQW-output.patch \
	file://0004-rtc-abx80x-Enable-XT-digital-calibration.patch \
	file://0005-rtc-abx80x-Improve-sqw-generation.patch \
	file://0006-rtc-abx80x-Improve-xt_calibration.patch \
	file://0007-rtc-abx80x-Add-sqw-binding-doc.patch \
	file://0008-rtc-abx80x-Add-xt_calibration-binding-doc.patch \
	file://0009-serial-imx-allow-passing-rs485-options.patch \
	file://0010-sdhci-esdhc-imx-Add-fsl-custom-usdhc-data.patch \
	file://0011-imx8m-nano-add-basic-support.patch \
	file://defconfig \
"
